# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/reference-2-1/#section=configuration for more details

version: 2.1

references:
  working_directory: /tmp/gh-pages

  load_image: &load_image
    docker:
      - image: circleci/node:lts

  install_dependencies: &install_dependencies
    run:
      name: install-dependencies
      command: |
        yarn install

  lint: &lint
    run:
      name: lint
      command: |
        yarn lint

  test: &test
    run:
      name: test
      command: |
        yarn test

  build: &build
    run:
      name: build
      command: |
        export ELASTIC_URL=$ELASTIC_URL_ENV
        export VALIDATOR_URL=$VALIDATOR_URL
        export VALIDATOR_REMOTE_URL=$VALIDATOR_REMOTE_URL
        yarn build-prod

  setup_ssh_gh_pages: &setup_ssh_gh_pages
    add_ssh_keys:
      fingerprints:
        # gh-pages deployment key from circle-ci config
        - 8d:51:1f:59:38:05:3b:37:34:96:11:c5:29:15:e7:5e

  deploy_gh_pages: &deploy_gh_pages
    run:
      name: deploy-gh-pages
      command: |
        echo publiccode-editor.developers.italia.it > dist/CNAME
        yarn run deploy -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]"

  # In order to use this, the integration needs to be
  # setup first under CircleCI app directory and a
  # SLACK_WEBOOK environment variable needs to be set
  # in the project settings
  notify_on_failure: &notify_on_failure
    slack/status:
      fail_only: true
      only_for_branches: master

jobs:
  build-and-test:
    <<: *load_image
    steps:
      - checkout
      - << : *install_dependencies
      - << : *lint
      - << : *test
      - << : *build
      - << : *notify_on_failure

  build-and-deploy-gh-pages:
    <<: *load_image
    steps:
      - checkout
      - << : *install_dependencies
      - << : *lint
      - << : *test
      - << : *build
      - << : *setup_ssh_gh_pages
      - << : *deploy_gh_pages
      - << : *notify_on_failure

orbs:
  slack: circleci/slack@3.4.2
  publiccode-parser: italia/publiccode-parser@0.0.3

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - publiccode-parser/validate
      - build-and-test:
          filters:
            branches:
                ignore:
                 - master
      - build-and-deploy-gh-pages:
          filters:
            branches:
              only:
                - master
